Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: torch in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: matplotlib in /home4/s5185491/.local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.9.0)
Requirement already satisfied: scikit-learn in /home4/s5185491/.local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.5.0)
Requirement already satisfied: numpy in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (1.25.1)
Requirement already satisfied: pandas in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (2.0.3)
Requirement already satisfied: xlrd in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (2.0.1)
Requirement already satisfied: statsmodels in /home4/s5185491/.local/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.14.2)
Requirement already satisfied: optuna in /home4/s5185491/.local/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (3.6.1)
Requirement already satisfied: plotly in /home4/s5185491/.local/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (5.22.0)
Requirement already satisfied: kaleido in /home4/s5185491/.local/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (0.2.1)
Requirement already satisfied: optuna-dashboard in /home4/s5185491/.local/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (0.15.1)
Requirement already satisfied: filelock in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.12.2)
Requirement already satisfied: typing-extensions in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (4.6.3)
Requirement already satisfied: sympy in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/sympy/1.12-gfbf-2023a/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/networkx/3.1-gfbf-2023a/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (2023.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /home4/s5185491/.local/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /home4/s5185491/.local/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home4/s5185491/.local/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home4/s5185491/.local/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (23.1)
Requirement already satisfied: pillow>=8 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Pillow/10.0.0-GCCcore-12.3.0/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (10.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from matplotlib->-r requirements.txt (line 2)) (2.8.2)
Requirement already satisfied: scipy>=1.6.0 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages (from scikit-learn->-r requirements.txt (line 3)) (1.11.1)
Requirement already satisfied: joblib>=1.2.0 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from scikit-learn->-r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from scikit-learn->-r requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: pytz>=2020.1 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from pandas->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages (from pandas->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: patsy>=0.5.6 in /home4/s5185491/.local/lib/python3.11/site-packages (from statsmodels->-r requirements.txt (line 7)) (0.5.6)
Requirement already satisfied: alembic>=1.5.0 in /home4/s5185491/.local/lib/python3.11/site-packages (from optuna->-r requirements.txt (line 8)) (1.13.1)
Requirement already satisfied: colorlog in /home4/s5185491/.local/lib/python3.11/site-packages (from optuna->-r requirements.txt (line 8)) (6.8.2)
Requirement already satisfied: sqlalchemy>=1.3.0 in /home4/s5185491/.local/lib/python3.11/site-packages (from optuna->-r requirements.txt (line 8)) (2.0.30)
Requirement already satisfied: tqdm in /home4/s5185491/.local/lib/python3.11/site-packages (from optuna->-r requirements.txt (line 8)) (4.66.4)
Requirement already satisfied: PyYAML in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/PyYAML/6.0-GCCcore-12.3.0/lib/python3.11/site-packages (from optuna->-r requirements.txt (line 8)) (6.0)
Requirement already satisfied: tenacity>=6.2.0 in /home4/s5185491/.local/lib/python3.11/site-packages (from plotly->-r requirements.txt (line 9)) (8.3.0)
Requirement already satisfied: bottle in /home4/s5185491/.local/lib/python3.11/site-packages (from optuna-dashboard->-r requirements.txt (line 11)) (0.12.25)
Requirement already satisfied: Mako in /home4/s5185491/.local/lib/python3.11/site-packages (from alembic>=1.5.0->optuna->-r requirements.txt (line 8)) (1.3.5)
Requirement already satisfied: six in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from patsy>=0.5.6->statsmodels->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: greenlet!=0.4.17 in /home4/s5185491/.local/lib/python3.11/site-packages (from sqlalchemy>=1.3.0->optuna->-r requirements.txt (line 8)) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages (from jinja2->torch->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages (from sympy->torch->-r requirements.txt (line 1)) (1.3.0)
Device: cuda
Traceback (most recent call last):
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: studies.study_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home4/s5185491/.local/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 264, in create_new_study
    with _create_scoped_session(self.scoped_session) as session:
  File "/cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/intel/skylake_avx512/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home4/s5185491/.local/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 73, in _create_scoped_session
    session.commit()
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2017, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
    self._flush(objects)
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4476, in _flush
    with util.safe_reraise():
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
    flush_context.execute()
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home4/s5185491/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: studies.study_name
[SQL: INSERT INTO studies (study_name) VALUES (?)]
[parameters: ('MLP-Tuning',)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home4/s5185491/test/NeuralNets-Project/main.py", line 95, in <module>
    study = create_study_and_pruner()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/test/NeuralNets-Project/main.py", line 31, in create_study_and_pruner
    study = optuna.create_study(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/optuna/study/study.py", line 1251, in create_study
    study_id = storage.create_new_study(direction_objects, study_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/optuna/storages/_cached_storage.py", line 82, in create_new_study
    study_id = self._backend.create_new_study(directions=directions, study_name=study_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/s5185491/.local/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py", line 276, in create_new_study
    raise optuna.exceptions.DuplicatedStudyError(
optuna.exceptions.DuplicatedStudyError: Another study with name 'MLP-Tuning' already exists. Please specify a different name, or reuse the existing one by setting `load_if_exists` (for Python API) or `--skip-if-exists` flag (for CLI).

###############################################################################
Hábrók Cluster
Job 9842112 for user s5185491
Finished at: Mon Jun 10 16:25:28 CEST 2024

Job details:
============

Job ID              : 9842112
Name                : train_job.sh
User                : s5185491
Partition           : gpushort
Nodes               : v100gpu[32,34]
Number of Nodes     : 2
Cores               : 16
Number of Tasks     : 2
State               : RUNNING
Submit              : 2024-06-10T16:15:29
Start               : 2024-06-10T16:24:42
End                 : --
Reserved walltime   : 04:00:00
Used walltime       : 00:00:46
Used CPU time       : --
% User (Computation): --
% System (I/O)      : --
Mem reserved        : 32G
Max Mem (Node/step) : 0.00  (Node unknown, N/A)
Full Max Mem usage  : 0.00  (Until last completed step)
Total Disk Read     : 0.00  (Until last completed step)
Total Disk Write    : 0.00  (Until last completed step)

Acknowledgements:
=================

Please see this page for information about acknowledging Hábrók in your publications:

https://wiki.hpc.rug.nl/habrok/introduction/scientific_output

################################################################################
